apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::397373384445:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1575SA8O4O4CI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::397373384445:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-26T20:10:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1364"
  uid: ed36f75e-9f40-48ed-95d6-fefaa787cb3e
